apiVersion: v1	
kind: Service	
metadata:	
  name: guestbook-ui	
#spec:	
 # ports:	
 # - port: 80	
  #  targetPort: 80	
  #selector:	
   # app: guestbook-ui
    
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: argo
    version: v3.0.0
  type: LoadBalancer
